// packages/mirror-react/src/polling.ts
import { useRef } from "react";
import { useQuery } from "@tanstack/react-query";
import type { UseQueryOptions, UseQueryResult } from "@tanstack/react-query";
import type { ApiResult, ApiError, TransactionDetails } from "@hieco/mirror";
import { useMirrorNodeClient, useNetwork } from "./context-hooks";
import { mirrorNodeKeys } from "@hieco/utils";

export interface UsePollTransactionOptions extends Omit<
  UseQueryOptions<ApiResult<TransactionDetails>, ApiError>,
  "queryKey" | "queryFn"
> {
  readonly transactionId: string;
  readonly maxAttempts?: number;
  readonly intervalMs?: number;
  readonly stopOnConfirmed?: boolean;
}

type UsePollTransactionResult = UseQueryResult<ApiResult<TransactionDetails>, ApiError>;

export function usePollTransaction(options: UsePollTransactionOptions): UsePollTransactionResult {
  const {
    transactionId,
    maxAttempts = 60,
    intervalMs = 1000,
    stopOnConfirmed = true,
    ...queryOptions
  } = options;

  const client = useMirrorNodeClient();
  const { network } = useNetwork();
  const attemptsRef = useRef(0);

  return useQuery({
    ...queryOptions,
    queryKey: mirrorNodeKeys.transaction.info(network, transactionId),
    queryFn: async () => {
      attemptsRef.current++;
      if (attemptsRef.current > maxAttempts) {
        throw new Error(`Transaction polling exceeded max attempts: ${maxAttempts}`);
      }
      return client.transaction.getById(transactionId);
    },
    refetchInterval: (query) => {
      const data = query.state.data;
      if (!data) return intervalMs;

      if (!data.success) {
        return false;
      }

      if (stopOnConfirmed) {
        const result = data.data.result;
        if (result === "SUCCESS") {
          return false;
        }
      }

      return intervalMs;
    },
    refetchIntervalInBackground: true,
  });
}

// packages/mirror-solid/src/polling.ts
import { useQuery } from "@tanstack/solid-query";
import { createSignal } from "solid-js";
import type { Accessor } from "solid-js";
import type { UseQueryResult } from "@tanstack/solid-query";
import type { ApiResult, ApiError, TransactionDetails } from "@hieco/mirror";
import { useMirrorNodeClient, useNetwork } from "./context-hooks";
import { mirrorNodeKeys } from "@hieco/utils";

export interface CreatePollTransactionOptions {
  readonly transactionId: string;
  readonly maxAttempts?: number;
  readonly intervalMs?: number;
  readonly stopOnConfirmed?: boolean;
  readonly enabled?: boolean;
}

type CreatePollTransactionResult = UseQueryResult<ApiResult<TransactionDetails>, ApiError>;

export function createPollTransaction(
  options: Accessor<CreatePollTransactionOptions>,
): CreatePollTransactionResult {
  const client = useMirrorNodeClient();
  const { network } = useNetwork();
  const attempts = createSignal(0);

  return useQuery(() => {
    const opts = options();
    const [attemptsValue, setAttempts] = attempts;

    return {
      queryKey: mirrorNodeKeys.transaction.info(network(), opts.transactionId),
      queryFn: async () => {
        setAttempts(attemptsValue() + 1);
        if (attemptsValue() > (opts.maxAttempts ?? 60)) {
          throw new Error(`Transaction polling exceeded max attempts: ${opts.maxAttempts}`);
        }
        return client().transaction.getById(opts.transactionId);
      },
      get refetchInterval() {
        return opts.intervalMs ?? 1000;
      },
      refetchIntervalInBackground: true,
    };
  });
}
