// packages/mirror-solid/src/balances/hooks.ts
import { useQuery } from "@tanstack/solid-query";
import type { UseQueryResult } from "@tanstack/solid-query";
import type { ApiResult, ApiError, QueryOperator } from "@hieco/mirror";
import type { BalancesResponse } from "@hieco/mirror";
import type { Accessor } from "solid-js";
import { useMirrorNodeClient, useNetwork } from "../context-hooks";
import { mirrorNodeKeys } from "@hieco/utils";

export type { BalancesListParams } from "@hieco/mirror";

export interface CreateBalancesOptions {
  readonly params?: {
    readonly limit?: number;
    readonly order?: "asc" | "desc";
    readonly account?: string;
    readonly "account.balance"?: QueryOperator<number>;
    readonly public_key?: string;
    readonly timestamp?: string;
  };
  readonly enabled?: boolean;
}

export type CreateBalancesResult = UseQueryResult<ApiResult<BalancesResponse>, ApiError>;

export function createBalances(
  options: Accessor<CreateBalancesOptions> = () => ({}),
): CreateBalancesResult {
  const client = useMirrorNodeClient();
  const { network } = useNetwork();

  return useQuery(() => {
    const opts = options();
    return {
      queryKey: mirrorNodeKeys.balance.list(network()),
      queryFn: async () => {
        return client().balance.getBalances(opts.params);
      },
      get enabled() {
        return opts.enabled ?? true;
      },
    };
  });
}

// packages/mirror-react/src/polling/hooks.ts
import { useRef } from "react";
import { useQuery } from "@tanstack/react-query";
import type { UseQueryOptions, UseQueryResult } from "@tanstack/react-query";
import type { ApiResult, ApiError, TransactionDetails } from "@hieco/mirror";
import { useMirrorNodeClient, useNetwork } from "../context-hooks";
import { mirrorNodeKeys } from "@hieco/utils";

export interface UsePollTransactionOptions extends Omit<
  UseQueryOptions<ApiResult<TransactionDetails>, ApiError>,
  "queryKey" | "queryFn"
> {
  readonly transactionId: string;
  readonly maxAttempts?: number;
  readonly intervalMs?: number;
  readonly stopOnConfirmed?: boolean;
}

export type UsePollTransactionResult = UseQueryResult<ApiResult<TransactionDetails>, ApiError>;

export function usePollTransaction(options: UsePollTransactionOptions): UsePollTransactionResult {
  const {
    transactionId,
    maxAttempts = 60,
    intervalMs = 1000,
    stopOnConfirmed = true,
    ...queryOptions
  } = options;

  const client = useMirrorNodeClient();
  const { network } = useNetwork();
  const attemptsRef = useRef(0);

  return useQuery({
    ...queryOptions,
    queryKey: mirrorNodeKeys.transaction.info(network, transactionId),
    queryFn: async () => {
      attemptsRef.current++;
      if (attemptsRef.current > maxAttempts) {
        throw new Error(`Transaction polling exceeded max attempts: ${maxAttempts}`);
      }
      return client.transaction.getById(transactionId);
    },
    refetchInterval: (query) => {
      const data = query.state.data;
      if (!data) return intervalMs;

      if (!data.success) {
        return false;
      }

      if (stopOnConfirmed) {
        const result = data.data.result;
        if (result === "SUCCESS") {
          return false;
        }
      }

      return intervalMs;
    },
    refetchIntervalInBackground: true,
  });
}
