// packages/mirror-solid/src/components/api-error-boundary.tsx
import type { JSX } from "solid-js";
import { ErrorBoundary, resetErrorBoundaries } from "solid-js";
import type { ApiError } from "@hieco/mirror-js";

export interface ApiErrorFallbackProps {
  error: ApiError;
  reset: () => void;
}

export interface ApiErrorBoundaryProps {
  readonly children: JSX.Element;
  readonly fallback: (props: ApiErrorFallbackProps) => JSX.Element;
}

export function ApiErrorBoundary(props: ApiErrorBoundaryProps): JSX.Element {
  return (
    <ErrorBoundary
      fallback={(error) => {
        const isApiError = (e: unknown): e is ApiError => {
          return (
            typeof e === "object" &&
            e !== null &&
            "_tag" in e &&
            "message" in e &&
            typeof (e as Record<string, unknown>)._tag === "string" &&
            typeof (e as Record<string, unknown>).message === "string"
          );
        };

        const apiError: ApiError = isApiError(error)
          ? error
          : {
            _tag: "UnknownError",
            message: error instanceof Error ? error.message : "Unknown error occurred",
          };

        return props.fallback({
          error: apiError,
          reset: () => resetErrorBoundaries(),
        });
      }}
    >
      {props.children}
    </ErrorBoundary>
  );
}

// packages/mirror-preact/src/components/api-error-boundary.tsx
import type { VNode } from "preact";
import { useErrorBoundary } from "preact/hooks";
import type { ApiError } from "@hieco/mirror-js";

export interface ApiErrorFallbackProps {
  error: ApiError;
  reset: () => void;
  render: (props: ApiErrorFallbackProps) => VNode;
}

export function ApiErrorFallback({ error, reset, render }: ApiErrorFallbackProps): VNode {
  return render({ error, reset, render });
}

export interface ApiErrorBoundaryProps {
  readonly children: VNode;
  readonly fallback: (props: ApiErrorFallbackProps) => VNode;
}

export function ApiErrorBoundary({ children, fallback }: ApiErrorBoundaryProps): VNode {
  const [error, resetError] = useErrorBoundary();

  if (error) {
    const apiError = toApiError(error);

    const reset = () => {
      resetError();
    };

    return <ApiErrorFallback error={apiError} reset={reset} render={fallback} />;
  }

  return children;
}

function toApiError(error: unknown): ApiError {
  if (isApiError(error)) {
    return error;
  }
  return {
    _tag: "UnknownError",
    message: error instanceof Error ? error.message : "Unknown error occurred",
  };
}

function isApiError(error: unknown): error is ApiError {
  return (
    typeof error === "object" && error !== null && "_tag" in error && typeof error._tag === "string"
  );
}

export function withApiErrorBoundary<P extends object>(
  Component: (props: P) => VNode,
  fallback: (props: ApiErrorFallbackProps) => VNode,
): (props: P) => VNode {
  return (props: P) => (
    <ApiErrorBoundary fallback={fallback}>
      <Component {...props} />
    </ApiErrorBoundary>
  );
}
