// packages/mirror-react/src/hooks/polling-hooks.ts
import { useRef } from "react";
import { useQuery } from "@tanstack/react-query";
import type { UseQueryOptions, UseQueryResult } from "@tanstack/react-query";
import type { ApiResult, ApiError, TransactionDetails } from "@hiecom/mirror-js";
import type { EntityId } from "@hiecom/mirror-js";
import { useMirrorNodeClient, useNetwork } from "../context-hooks";
import { mirrorNodeKeys, isSuccess, isApiError } from "@hiecom/mirror-shared";

export interface UsePollTransactionOptions extends Omit<
  UseQueryOptions<ApiResult<TransactionDetails>, ApiError>,
  "queryKey" | "queryFn"
> {
  readonly transactionId: EntityId;
  readonly maxAttempts?: number;
  readonly intervalMs?: number;
  readonly stopOnConfirmed?: boolean;
}

export type UsePollTransactionResult = UseQueryResult<ApiResult<TransactionDetails>, ApiError>;

export function usePollTransaction(options: UsePollTransactionOptions): UsePollTransactionResult {
  const {
    transactionId,
    maxAttempts = 60,
    intervalMs = 1000,
    stopOnConfirmed = true,
    ...queryOptions
  } = options;

  const client = useMirrorNodeClient();
  const { network } = useNetwork();
  const attemptsRef = useRef(0);

  return useQuery({
    ...queryOptions,
    queryKey: mirrorNodeKeys.transaction.info(network, transactionId),
    queryFn: async () => {
      attemptsRef.current++;
      if (attemptsRef.current > maxAttempts) {
        throw new Error(`Transaction polling exceeded max attempts: ${maxAttempts}`);
      }
      return client.transaction.getById(transactionId);
    },
    refetchInterval: (query) => {
      const data = query.state.data;
      if (!data) return intervalMs;

      if (isApiError(data)) {
        return false;
      }

      if (stopOnConfirmed && isSuccess(data)) {
        const result = data.data.result;
        if (result === "SUCCESS") {
          return false;
        }
      }

      return intervalMs;
    },
    refetchIntervalInBackground: true,
  });
}

// packages/unfinished_solid-mirror-node/src/adapters/solid-query/hooks/polling-hooks.ts
import { createSignal } from "solid-js";
import { useQuery } from "@tanstack/solid-query";
import type { UseQueryOptions, UseQueryResult } from "@tanstack/solid-query";
import type { ApiResult, ApiError, TransactionDetails } from "@hiecom/mirror-node";
import type { EntityId } from "@hiecom/mirror-node";
import { useMirrorNodeClient, useNetwork } from "../../../solid/hooks";
import { mirrorNodeKeys } from "../query-keys";
import { isSuccess, isApiError } from "../utils/type-guards";
import type { Accessor } from "solid-js";

export interface UsePollTransactionOptions extends Omit<
  UseQueryOptions<ApiResult<TransactionDetails>, ApiError>,
  "queryKey" | "queryFn"
> {
  transactionId: Accessor<EntityId>;
  maxAttempts?: number;
  intervalMs?: number;
  stopOnConfirmed?: boolean;
}

export type UsePollTransactionResult = UseQueryResult<ApiResult<TransactionDetails>, ApiError>;

export function usePollTransaction(options: UsePollTransactionOptions): UsePollTransactionResult {
  const {
    transactionId,
    maxAttempts = 60,
    intervalMs = 1000,
    stopOnConfirmed = true,
  } = options;

  const client = useMirrorNodeClient();
  const { network } = useNetwork();
  const [attempts, setAttempts] = createSignal(0);

  return useQuery(() => ({
    queryKey: mirrorNodeKeys.transaction.info(network(), transactionId()),
    queryFn: async () => {
      setAttempts((prev) => prev + 1);
      if (attempts() > maxAttempts) {
        throw new Error(`Transaction polling exceeded max attempts: ${maxAttempts}`);
      }
      return client().transaction.getById(transactionId());
    },
    refetchInterval: (query) => {
      const data = query.state.data;
      if (!data) return intervalMs;

      if (isApiError(data)) {
        return false;
      }

      if (stopOnConfirmed && isSuccess(data)) {
        const result = data.data.result;
        if (result === "SUCCESS") {
          return false;
        }
      }

      return intervalMs;
    },
    refetchIntervalInBackground: true,
  }));
}
