// packages/mirror-react/src/polling/hooks.ts
import { useRef } from "react";
import { useQuery } from "@tanstack/react-query";
import type { UseQueryOptions, UseQueryResult } from "@tanstack/react-query";
import type { ApiResult, ApiError, TransactionDetails } from "@hieco/mirror";
import { useMirrorNodeClient, useNetwork } from "../context-hooks";
import { mirrorNodeKeys } from "@hieco/utils";

export interface UsePollTransactionOptions extends Omit<
  UseQueryOptions<ApiResult<TransactionDetails>, ApiError>,
  "queryKey" | "queryFn"
> {
  readonly transactionId: string;
  readonly maxAttempts?: number;
  readonly intervalMs?: number;
  readonly stopOnConfirmed?: boolean;
}

export type UsePollTransactionResult = UseQueryResult<ApiResult<TransactionDetails>, ApiError>;

export function usePollTransaction(options: UsePollTransactionOptions): UsePollTransactionResult {
  const {
    transactionId,
    maxAttempts = 60,
    intervalMs = 1000,
    stopOnConfirmed = true,
    ...queryOptions
  } = options;

  const client = useMirrorNodeClient();
  const { network } = useNetwork();
  const attemptsRef = useRef(0);

  return useQuery({
    ...queryOptions,
    queryKey: mirrorNodeKeys.transaction.info(network, transactionId),
    queryFn: async () => {
      attemptsRef.current++;
      if (attemptsRef.current > maxAttempts) {
        throw new Error(`Transaction polling exceeded max attempts: ${maxAttempts}`);
      }
      return client.transaction.getById(transactionId);
    },
    refetchInterval: (query) => {
      const data = query.state.data;
      if (!data) return intervalMs;

      if (!data.success) {
        return false;
      }

      if (stopOnConfirmed) {
        const result = data.data.result;
        if (result === "SUCCESS") {
          return false;
        }
      }

      return intervalMs;
    },
    refetchIntervalInBackground: true,
  });
}

// packages/mirror-solid/src/blocks/hooks.ts
import { useQuery } from "@tanstack/solid-query";
import type { UseQueryResult } from "@tanstack/solid-query";
import type { ApiResult, ApiError } from "@hieco/mirror";
import type { BlocksResponse, Block } from "@hieco/mirror";
import type { Accessor } from "solid-js";
import { useMirrorNodeClient, useNetwork } from "../context-hooks";
import { mirrorNodeKeys } from "@hieco/utils";

export type { BlocksListParams } from "@hieco/mirror";

export interface CreateBlocksOptions {
  readonly params?: {
    readonly limit?: number;
    readonly order?: "asc" | "desc";
    readonly block_number?: number;
    readonly timestamp?: string;
  };
  readonly enabled?: boolean;
}

export type CreateBlocksResult = UseQueryResult<ApiResult<BlocksResponse>, ApiError>;

export interface CreateBlockOptions {
  readonly hashOrNumber: string;
  readonly enabled?: boolean;
}

export type CreateBlockResult = UseQueryResult<ApiResult<Block>, ApiError>;

export function createBlocks(
  options: Accessor<CreateBlocksOptions> = () => ({}),
): CreateBlocksResult {
  const client = useMirrorNodeClient();
  const { network } = useNetwork();

  return useQuery(() => {
    const opts = options();
    return {
      queryKey: mirrorNodeKeys.block.list(network()),
      queryFn: async () => {
        return client().block.getBlocks(opts.params);
      },
      get enabled() {
        return opts.enabled ?? true;
      },
    };
  });
}

export function createBlock(options: Accessor<CreateBlockOptions>): CreateBlockResult {
  const client = useMirrorNodeClient();
  const { network } = useNetwork();

  return useQuery(() => {
    const opts = options();
    return {
      queryKey: mirrorNodeKeys.block.info(network(), opts.hashOrNumber),
      queryFn: async () => {
        return client().block.getBlock(opts.hashOrNumber);
      },
      get enabled() {
        return opts.enabled ?? true;
      },
    };
  });
}
