// packages/preact-mirror-node/src/preact/components/api-error-boundary.tsx
import type { VNode } from "preact";
import { useErrorBoundary } from "preact/hooks";
import type { ApiError } from "@hiecom/mirror-node";

export interface ApiErrorFallbackProps {
  error: ApiError;
  reset: () => void;
  render: (props: ApiErrorFallbackProps) => VNode;
}

export function ApiErrorFallback({ error, reset, render }: ApiErrorFallbackProps): VNode {
  return render({ error, reset, render });
}

export interface ApiErrorBoundaryProps {
  readonly children: VNode;
  readonly fallback: (props: ApiErrorFallbackProps) => VNode;
}

export function ApiErrorBoundary({ children, fallback }: ApiErrorBoundaryProps): VNode {
  const [error, resetError] = useErrorBoundary();

  if (error) {
    const apiError = toApiError(error);

    const reset = () => {
      resetError();
    };

    return <ApiErrorFallback error={apiError} reset={reset} render={fallback} />;
  }

  return children;
}

function toApiError(error: unknown): ApiError {
  if (isApiError(error)) {
    return error;
  }
  return {
    _tag: "UnknownError",
    message: error instanceof Error ? error.message : "Unknown error occurred",
  };
}

function isApiError(error: unknown): error is ApiError {
  return (
    typeof error === "object" && error !== null && "_tag" in error && typeof error._tag === "string"
  );
}

export function withApiErrorBoundary<P extends object>(
  Component: (props: P) => VNode,
  fallback: (props: ApiErrorFallbackProps) => VNode,
): (props: P) => VNode {
  return (props: P) => (
    <ApiErrorBoundary fallback={fallback}>
      <Component {...props} />
    </ApiErrorBoundary>
  );
}

// packages/unfinished_solid-mirror-node/src/solid/components/api-error-boundary.tsx
import { ErrorBoundary as SolidErrorBoundary, type ParentComponent, type JSX } from "solid-js";
import type { ApiError } from "@hiecom/mirror-node";

export interface ApiErrorFallbackProps {
  error: ApiError;
  reset: () => void;
  render: (props: ApiErrorFallbackProps) => JSX.Element;
}

export function ApiErrorFallback(props: ApiErrorFallbackProps): JSX.Element {
  return props.render(props);
}

export interface ApiErrorBoundaryProps {
  children?: JSX.Element;
  fallback: (props: ApiErrorFallbackProps) => JSX.Element;
}

export interface ApiErrorBoundaryState {
  readonly error: ApiError | null;
}

export function ApiErrorBoundary(props: ApiErrorBoundaryProps): JSX.Element {
  return (
    <SolidErrorBoundary
      fallback={(error) => {
        const apiError = isApiError(error)
          ? error
          : {
              _tag: "UnknownError" as const,
              message: error instanceof Error ? error.message : "Unknown error occurred",
            };
        return props.fallback({
          error: apiError,
          reset: () => window.location.reload(),
          render: props.fallback,
        });
      }}
    >
      {props.children}
    </SolidErrorBoundary>
  );
}

function isApiError(error: unknown): error is ApiError {
  return typeof error === "object" && error !== null && "_tag" in error && typeof error._tag === "string";
}

export function withApiErrorBoundary<P extends object>(
  Component: (props: P) => JSX.Element,
  fallback: (props: ApiErrorFallbackProps) => JSX.Element,
): (props: P) => JSX.Element {
  return (props: P) => (
    <ApiErrorBoundary fallback={fallback}>
      <Component {...props} />
    </ApiErrorBoundary>
  );
}
