// packages/mirror-solid/src/context-hooks.ts
import { useContext } from "solid-js";
import { MirrorNodeContext } from "./provider";
import type { MirrorNodeClient } from "@hieco/mirror";
import type { MirrorNodeContextValue } from "./provider";

export function useMirrorNodeContext(): MirrorNodeContextValue {
  const context = useContext(MirrorNodeContext);

  if (!context) {
    throw new Error("useMirrorNodeContext must be used within a MirrorNodeProvider");
  }

  return context;
}

export function useMirrorNodeClient(): () => MirrorNodeClient {
  const { client } = useMirrorNodeContext();
  return client;
}

export function useNetwork(): Pick<
  MirrorNodeContextValue,
  "network" | "mirrorNodeUrl" | "switchNetwork"
> {
  const { network, mirrorNodeUrl, switchNetwork } = useMirrorNodeContext();

  return {
    network,
    mirrorNodeUrl,
    switchNetwork,
  };
}

export type { MirrorNodeContextValue };

// packages/realtime-react/src/context-hooks.ts
import { useContext, useState } from "react";
import { RealtimeContext } from "./provider";
import type { RealtimeContextValue } from "./provider";
import type { StreamState, RelayWebSocketClient } from "@hieco/realtime";
import type { ApiResult } from "@hieco/mirror-js";

export function useRealtimeContext(): RealtimeContextValue {
  const context = useContext(RealtimeContext);
  if (context === null) {
    throw new Error("useRealtimeContext must be used within a RealtimeProvider");
  }
  return context;
}

export function useRealtimeClient(): RelayWebSocketClient {
  const { client } = useRealtimeContext();
  return client;
}

export function useStreamState(): StreamState {
  const { state } = useRealtimeContext();
  return state;
}

export function useChainId(): {
  getChainId: () => Promise<ApiResult<string>>;
  result: ApiResult<string> | null;
} {
  const { client } = useRealtimeContext();
  const [result, setResult] = useState<ApiResult<string> | null>(null);

  const getChainId = () => {
    const promise = client.getChainId();
    promise.then(setResult);
    return promise;
  };

  return { getChainId, result };
}
