// packages/mirror-react/src/polling/hooks.ts
import { useRef } from "react";
import { useQuery } from "@tanstack/react-query";
import type { UseQueryOptions, UseQueryResult } from "@tanstack/react-query";
import type { ApiResult, ApiError, TransactionDetails } from "@hieco/mirror";
import type { EntityId } from "@hieco/mirror";
import { useMirrorNodeClient, useNetwork } from "../context-hooks";
import { mirrorNodeKeys } from "@hieco/utils";

export interface UsePollTransactionOptions extends Omit<
  UseQueryOptions<ApiResult<TransactionDetails>, ApiError>,
  "queryKey" | "queryFn"
> {
  readonly transactionId: EntityId;
  readonly maxAttempts?: number;
  readonly intervalMs?: number;
  readonly stopOnConfirmed?: boolean;
}

export type UsePollTransactionResult = UseQueryResult<ApiResult<TransactionDetails>, ApiError>;

export function usePollTransaction(options: UsePollTransactionOptions): UsePollTransactionResult {
  const {
    transactionId,
    maxAttempts = 60,
    intervalMs = 1000,
    stopOnConfirmed = true,
    ...queryOptions
  } = options;

  const client = useMirrorNodeClient();
  const { network } = useNetwork();
  const attemptsRef = useRef(0);

  return useQuery({
    ...queryOptions,
    queryKey: mirrorNodeKeys.transaction.info(network, transactionId),
    queryFn: async () => {
      attemptsRef.current++;
      if (attemptsRef.current > maxAttempts) {
        throw new Error(`Transaction polling exceeded max attempts: ${maxAttempts}`);
      }
      return client.transaction.getById(transactionId);
    },
    refetchInterval: (query) => {
      const data = query.state.data;
      if (!data) return intervalMs;

      if (!data.success) {
        return false;
      }

      if (stopOnConfirmed) {
        const result = data.data.result;
        if (result === "SUCCESS") {
          return false;
        }
      }

      return intervalMs;
    },
    refetchIntervalInBackground: true,
  });
}

// packages/mirror-solid/src/transactions/hooks.ts
import { useQuery } from "@tanstack/solid-query";
import type { UseQueryResult, UseInfiniteQueryResult } from "@tanstack/solid-query";
import type {
  ApiResult,
  ApiError,
  EntityId,
  QueryOperator,
  Timestamp,
  TransactionDetails,
  Transaction,
} from "@hieco/mirror";
import type { PaginatedResponse } from "@hieco/mirror";
import type { Accessor } from "solid-js";
import { useMirrorNodeClient, useNetwork } from "../context-hooks";
import { mirrorNodeKeys } from "@hieco/utils";
import { createMirrorNodeInfiniteQuery } from "../polling/infinite";

export type { TransactionListParams, TransactionsByAccountParams } from "@hieco/mirror";

export interface CreateTransactionOptions {
  readonly transactionId: string;
  readonly enabled?: boolean;
}

export type CreateTransactionResult = UseQueryResult<ApiResult<TransactionDetails>, ApiError>;

export interface CreateTransactionsByAccountOptions {
  readonly accountId: EntityId;
  readonly params?: {
    readonly limit?: number;
    readonly order?: "asc" | "desc";
    readonly timestamp?: Timestamp | { readonly from?: Timestamp; readonly to?: Timestamp };
    readonly transaction_id?: string;
    readonly result?: string;
  };
  readonly enabled?: boolean;
}

export type CreateTransactionsByAccountResult = UseQueryResult<ApiResult<Transaction[]>, ApiError>;

export interface CreateTransactionsOptions {
  readonly params?: {
    readonly limit?: number;
    readonly order?: "asc" | "desc";
    readonly account?: EntityId;
    readonly "account.id"?: EntityId | QueryOperator<EntityId>;
    readonly transaction_id?: string;
    readonly result?: string;
  };
  readonly enabled?: boolean;
}

export type CreateTransactionsResult = UseQueryResult<ApiResult<Transaction[]>, ApiError>;

export interface CreateTransactionsInfiniteOptions {
  readonly params?: { readonly limit?: number; readonly order?: "asc" | "desc" };
  readonly enabled?: boolean;
}

export type CreateTransactionsInfiniteResult = UseInfiniteQueryResult<
  ApiResult<PaginatedResponse<Transaction>>,
  ApiError
>;

export function createTransaction(
  options: Accessor<CreateTransactionOptions>,
): CreateTransactionResult {
  const client = useMirrorNodeClient();
  const { network } = useNetwork();

  return useQuery(() => {
    const opts = options();
    return {
      queryKey: mirrorNodeKeys.transaction.info(network(), opts.transactionId),
      queryFn: async () => {
        return client().transaction.getById(opts.transactionId);
      },
      get enabled() {
        return opts.enabled ?? true;
      },
    };
  });
}

export function createTransactionsByAccount(
  options: Accessor<CreateTransactionsByAccountOptions>,
): CreateTransactionsByAccountResult {
  const client = useMirrorNodeClient();
  const { network } = useNetwork();

  return useQuery(() => {
    const opts = options();
    return {
      queryKey: mirrorNodeKeys.transaction.byAccount(network(), opts.accountId),
      queryFn: async () => {
        return client().transaction.listByAccount(opts.accountId, opts.params);
      },
      get enabled() {
        return opts.enabled ?? true;
      },
    };
  });
}

export function createTransactions(
  options: Accessor<CreateTransactionsOptions> = () => ({}),
): CreateTransactionsResult {
  const client = useMirrorNodeClient();
  const { network } = useNetwork();

  return useQuery(() => {
    const opts = options();
    return {
      queryKey: mirrorNodeKeys.transaction.list(network()),
      queryFn: async () => {
        return client().transaction.listPaginated(opts.params);
      },
      get enabled() {
        return opts.enabled ?? true;
      },
    };
  });
}

export function createTransactionsInfinite(
  options: Accessor<CreateTransactionsInfiniteOptions>,
): CreateTransactionsInfiniteResult {
  const client = useMirrorNodeClient();
  const { network } = useNetwork();

  return createMirrorNodeInfiniteQuery(
    mirrorNodeKeys.transaction.list(network()),
    options,
    (pageParam, opts) => {
      if (pageParam) {
        return client().transaction.listPaginatedPageByUrl(pageParam);
      }
      return client().transaction.listPaginatedPage({
        ...opts.params,
        limit: opts.params?.limit ?? 25,
      });
    },
    (lastPage) => {
      if (!lastPage.success) return undefined;
      return lastPage.data.links.next ?? undefined;
    },
  );
}
